apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-master-deployment
  labels:
    app: shopping-cart-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-master
  template:
    metadata:
      labels:
        app: shopping-cart-master
    spec:
      containers:
        - name: shopping-cart-master
          image: git.hub.com/myimage
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256M
            limits:
              cpu: "1"
              memory: 1G
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 6
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 6
            timeoutSeconds: 10
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: shopping-cart-master-config