apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-master-service
spec:
  selector:
    app:  shopping-cart-master
  ports:
    - name: https
      port: 443
      targetPort: 8080
  type: LoadBalancer
